### ISSUE TITLE
SUBTLETY - heading font-size

### ISSUE THREAD

**Issue by franfranfranfran** [pkanteti/dasmotos-arts#1]
check out the font-size of the main h1 heading and each section's h2 heading. they look a bit large, but you are setting the font-size right in the css. if you use devtools to inspect these elements, the h1 is actually 200px and the h2 is 48px. so what is happening here?

many elements have default styling that is provided by a browser if no other styling is found. you can check out some more info about heading default styling here - https://www.w3schools.com/TAgs/tag_hn.asp  the default for h1 elements is 2em, which means 2 times the current font-size. you set 100px for the div that surrounds the h1 element. so that 2em is never overwritten and the text ends up with 2 times 100px, which is 200px. 
h2's default is 1.5em which is how that ends up with 48px instead of 32px.

so you have a couple options here:
- set the font-size for the divs with these calculations in mind (50px for the main heading div, etc...). but this could be confusing down the line
- target the element directly and set the font-size that you want, overwriting the default

this all might be a bit much for now, but you'll learn more about default styling and em values in exercises to come.

**Comment by pkanteti** [comment]
Updated the code to remove the redundant divs and to use the targeted selector to override the browser defaults.
