### ISSUE TITLE
SUBTLETY - div structure

### ISSUE THREAD

**Issue by franfranfranfran** [pkanteti/dasmotos-arts#2]
excellent work using divs and classes to help structure and label the content on the page. check out the example below for a potentially more straight-forward way to accomplish the same effect -

```
<div class="item">
    <h2 id="frames">Frames</h2>
    <img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/frames.jpeg" alt="Frames">
    <h3>Art Frames (assorted)</h3>
    <p>Assorted frames made of different material, including MDF, birchwood, and PDE. Select frames can be sanded and painted according to your needs. <span class="price-tag">Starting at $2.00 / frame.</span></p>
</div>
```

here we just have one div around the whole section to separate it from the other two. the div is given a general 'item' class name that we could use to style the section as a whole if we wanted to. that way all three sections could be targeted at once and styled similarly. the element that is styled uniquely, h2, is given an id directly. this way you can use the id in your css to target that element directly and add whatever styling is needed.

there are many ways to accomplish the same task, so this isn't necessarily the only way to go about this project. just one example highlighting a simpler approach.

**Comment by pkanteti** [comment]
simplified the div structure
