### ISSUE TITLE
IMPORTANT - local images

### ISSUE THREAD

**Issue by franfranfranfran** [pkanteti/dasmotos-arts#4]
it is important to save your image files locally. links to outside sources can easily become broken if that source decides to change where they are stored or take them down entirely. saving locally ensures that you always know exactly where they are. 

save your images locally to an 'images' folder inside of resources and then use relative file paths to link to those from your html and css. The link to css currently on line 3 of your html is a great example or a relative path and more info can be found here - http://www.coffeecup.com/help/articles/absolute-vs-relative-pathslinks/

**Comment by pkanteti** [comment]
downloaded all the images and updated the code to use relative paths instead of external URLs.
