### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by franfranfranfran** [pkanteti/dasmotos-arts#5]
**GRADE**: Meets Expectations

**SUMMARY**: Good work on this project! After some quick fixes with font-size, the site will be looking great! Excellent work keeping both the project folder and the code itself neat, organized, and readable. Good idea to use divs, classes, and ids to help organize and structure the content of the page as well.

As you're setting your styling and creating your classes, always keep an eye on the end result. Load up the page and make sure the styling is being applied how you expect it to. Use [dev tools](https://www.codecademy.com/articles/use-devtools) to inspect and see where any differences might be coming from. Also, be sure to use locally saved images and relative file paths to link to them throughout the html and css. This will ensure that the page stays looking great and that you always know where your resources are.

As a next step, try restructuring the page a bit and see if you can get those font sizes to match up with the spec. Keep up the great work!

**Comment by pkanteti** [comment]
Fixed all the issues mentioned in the review.
